common/urls.py
# urls.py

from . import views
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'


urlpatterns = [
    # LoginView는 registration이라는 템플릿 디렉터리에서 login.html 파일을 찾는다.
    # 따라서 login.html 파일을 작성해야 한다.
    # as_view 함수에 template_name으로 'common/login.html'을 설정하면 registration 디렉터리가 아닌 common 디렉터리에서 login.html 파일을 참조하게 된다.
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup')
]

config/urls.py
from django.conf import settings  # 추가
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pybo/", include("pybo.urls")),
    path("common/", include("common.urls")),
    path("", base_views.index, name="index"),  # '/' 에 해당되는 path
]

# 디버그 툴바 설정
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

# handler404 변수는 좀 특별한 변수이다. 
# handler404 변수를 설정하면 404 오류 발생 시 사용자가 정의한 뷰 함수를 호출하게 된다. 
# 따라서 404 오류가 발생하면 위에 정의한 대로 common/views.py 파일의 page_not_found 함수가 호출된다.
handler404 = 'common.views.page_not_found'

pybo/urls.py
# urls.py
from django.urls import path  # django.urls 패키지에서 path 모듈 가져옴

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = "pybo"  # 네임스페이스 정의

urlpatterns = [
    #
    # base_views.py
    #
    # == path('', base_views.IndexView.as_view()),
    path("", base_views.index, name="index"),
    # == path('<int:pk>/', base_views.DetailView.as_view()),
    path("<int:question_id>/", base_views.detail, name="detail"),
    #
    # question_views.py
    #
    # {% url 'pybo:question_create' %}이 추가되었으니 pybo/urls.py 파일에 URL 매핑을 추가
    path("question/create/", question_views.question_create, name="question_create"),
    path("question/modify/<int:question_id>/", question_views.question_modify, name="question_modify"),  # 질문 수정 버튼의 URL 매핑 추가
    path("question/delete/<int:question_id>/", question_views.question_delete, name="question_delete"),  # 질문 삭제 URL 매핑 추가
    #
    # answer_views.py
    #
    path("answer/create/<int:question_id>/", answer_views.answer_create, name="answer_create"),
    path("answer/modify/<int:answer_id>/", answer_views.answer_modify, name="answer_modify"),  # 답변 수정 URL 매핑 추가
    path("answer/delete/<int:answer_id>/", answer_views.answer_delete, name="answer_delete"),  # 답변 삭제 URL 매핑 추가
    #
    # comment_views.py
    #
    # 질문 댓글 URL 매핑 추가
    path("comment/create/question/<int:question_id>/", comment_views.comment_create_question, name="comment_create_question"),  # 댓글 등록
    path("comment/modify/question/<int:comment_id>/", comment_views.comment_modify_question, name="comment_modify_question"),  # 댓글 수정
    path("comment/delete/question/<int:comment_id>/", comment_views.comment_delete_question, name="comment_delete_question"),  # 댓글 삭제
    # 답변 댓글 URL 매핑 추가
    path("comment/create/answer/<int:answer_id>/", comment_views.comment_create_answer, name="comment_create_answer"),  # 댓글 등록
    path("comment/modify/answer/<int:comment_id>/", comment_views.comment_modify_answer, name="comment_modify_answer"),  # 댓글 수정
    path("comment/delete/answer/<int:comment_id>/", comment_views.comment_delete_answer, name="comment_delete_answer"),  # 댓글 삭제
    #
    # vote_views.py
    #
    path("vote/question/<int:question_id>/", vote_views.vote_question, name="vote_question"),  # 질문 추천 URL 매핑
    path("vote/answer/<int:answer_id>/", vote_views.vote_answer, name="vote_answer"),  # 답변 추천 URL 매핑
]

pybo/views/base_views.py
# base_views.py
# 기본 관리

# 페이징 기능 구현
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from django.db.models import Q, Count

from ..models import Question

import logging
logger = logging.getLogger('pybo')

def index(request):
    
    # pybo 로거 생성하기
    logger.info("INFO 레벨로 출력")

    """
    pybo 목록출력
    """

    # 입력 파라미터
    page = request.GET.get("page", "1")  # 페이지
    kw = request.GET.get("kw", "")  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # order_by 함수는 조회한 데이터를 특정 속성으로 정렬하며, '-create_date'는
    # - 기호가 앞에 붙어 있으므로 작성일시의 역순을 의미한다.
    # 정렬
    if so == 'recommend':
        # 추천 수가 큰 것부터 정렬하므로 order_by에 추천 수 -num_voter를 입력
        # Question.objects.annotate(num_voter=Count('voter'))에서 사용한 annotate 함수는 
        # Question 모델의 기존 필드인 author, subject, content, create_date, modify_date, voter에 
        # 질문의 추천 수에 해당하는 num_voter 필드를 임시로 추가해 주는 함수이다.
        # 이렇게 annotate 함수로 num_voter 필드를 추가하면 filter 함수나 order_by 함수에서 
        # num_voter 필드를 사용할 수 있게 된다. 여기서 num_voter는 Count('voter')와 같이 
        # Count 함수를 사용하여 만들었다. Count('voter')는 해당 질문의 추천 수이다.
        # order_by('-num_voter', '-create_date')와 같이 order_by 함수에 두 개 이상의 인자가 전달되는 경우 
        # 1번째 항목부터 우선순위를 매긴다. 즉, 추천 수가 같으면 최신순으로 정렬한다.
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    # Q 함수에 사용된 subject__icontains=kw는 제목에 kw 문자열이 포함되었는지를 의미한다.
    # answer__author__username__icontains은 답변을 작성한 사람의 이름에 포함되는지를 의미한다.
    # filter 함수에서 모델 필드에 접근하려면 이처럼 __를 이용하면 된다.
    # subject__contains=kw 대신 subject__icontains=kw을 사용하면 대소문자를 가리지 않고 찾아 준다.
    # 1개의 질문에는 여러 개의 답변이 있을수 있으므로 답변자 중복을 처리하기 위해 distinct 함수를 반드시 사용해야 한다.
    if kw:
        # 제목검색 or 내용검색 or 질문 글쓴이검색 or 답변 글쓴이검색
        question_list = question_list.filter(
            Q(subject__icontains=kw) | 
            Q(content__icontains=kw) | 
            Q(author__username__icontains=kw) | 
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, "page": page, "kw": kw, 'so': so}  # page와 kw, so가 추가되었다.

    # render 함수는 context에 있는 Question 모델 데이터 question_list를
    # pybo/question_list.html 파일에 적용하여 HTML 코드로 변환한다.
    return render(request, "pybo/question_list.html", context)


def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {"question": question}
    return render(request, "pybo/question_detail.html", context)


# class IndexView(generic.ListView):
#     """
#     pybo 목록 출력
#     """
#     def get_queryset(self):
#         return Question.objects.order_by('-create_date')


# class DetailView(generic.DetailView):
#     """
#     pybo 내용 출력
#     """
#     model = Question

templates/base.html
<!-- base.html -->
<!-- body 엘리먼트에 % block content %와 % endblock % 템플릿 태그가 있다. 
	바로 이 부분이 이후 base.html 템플릿 파일을 상속한 파일에서 구현해야 하는 영역이 된다. -->

{% load static %}
<!doctype html>
<html lang="ko">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
	<!-- pybo CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<title>Hello, pybo!</title>
</head>

<body>
	<!-- 네비게이션바 -->
	<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
		<a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
		<button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
			aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item ">
					<a class="nav-link" href="#">로그인</a>
				</li>
			</ul>
		</div>
	</nav> -->
	<!-- navbar.html로 코드 이동 -->
	{% include "navbar.html" %}

	<!-- 기본 템플릿 안에 삽입될 내용 Start -->
	{% block content %}
	{% endblock %}
	<!-- 기본 템플릿 안에 삽입될 내용 End -->
	
	<!-- jQuery JS -->
	<script src="{% static 'jquery-3.4.1.min.js' %}"></script>
	<!-- Bootstrap JS -->
	<script src="{% static 'bootstrap.min.js' %}"></script>

	<!-- 자바스크립트 Start -->
	{% block script %}
	{% endblock %}
	<!-- 자바스크립트 End -->
</body>

</html>

templates/form_errors.html
<!-- form_errors.html -->

{% if form.errors %}
    {% for field in form %}
			{% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
					<div class="alert alert-danger">
							<strong>{{ field.label }}</strong>
							{{ error }}
					</div>
			{% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
			<div class="alert alert-danger">
					<strong>{{ error }}</strong>
			</div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- navbar.html -->

<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
	<a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
	<button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
		aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item ">
				<!-- % if user.is_authenticated %은 현재 로그인 상태를 판별하여 로그인 상태라면 로그아웃 링크를, 
					로그아웃 상태라면 로그인 링크를 보여 준다. 로그인 상태에서는 로그인한 사용자명 user.username 도 표시했다. -->
				{% if user.is_authenticated %}
					<a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
				{% else %}
				<!-- common/urls.py 파일에 URL 매핑 -->
					<a class="nav-link" href="{% url 'common:login' %}">로그인</a> 
				{% endif %}
			</li>
		</ul>
	</div>
</nav>